<a href="https://colab.research.google.com/github/saxena07/Google-Colab-Python/blob/main/A1_19102026_Lakshya_Saxena_lab_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Experiment 1**
## **Aim:** Introduction to Python and its various applications. 
##**Theory:**
  # Python
• High level, interpreted, and general-purpose dynamic programming
language.

###open Google colab in your browser,then new file


**Overview of Google Colab Interface**

1. Two **main ingredients** in a notebook are:
  * **Kernels**: The "computational engine" which executes code blocks of the notebook
  * **Cells**: A container for code or text (e.g., this is written within a markdown cell)
  * **Text** cell uses **markdown language**. If you're unfamiliar with Markdown syntax, check our this [cheat sheet](https://www.markdownguide.org/cheat-sheet).
   * **Code** cell contains **Python** code. Few important key-shortcuts while using **Code** cell:
    >* `Shift + Enter`: Executes the current cell and moves to the next
    >* `Shift + Tab`: Brings up documentation. Try this after entering `np.ones(`
 # Inserting Module
 ## What is a module?
 Certain functions are always defined, split(), len(<list>). But to access more
functions, must import their module.
* import <module name> is equivalent to #include <name>.h in C and C++
### Module:
  * A file containing functions, definitions, and/or executable statements.
  * The module name is just the file name with .py removed.
  * To import:
# Method 1 (Recommended)
import module1 as mod1

    mod1.some_func()
# Vectors, Matrices, and Arrays

### 1.0 Introduction
Numpy is the foundation of the Python machine learning stack. It allows for efficient operations on the data structures often used in machine learning: vectors, matricies, and tensors.

This chapter covers the most common NumPy operations we are likely to run into

### 1.1 Creating a Vector
#### Problem
You need to create a vector
#### Solution
Use Numpy to create a one-dimensional array

In [ ]:
# load library
import numpy as np

# create a vector as a row
vector_row=np.array([2, 5, 6])
print(vector_row)

# create a vetor as a column
vector_column=np.array([[1],[6],[3]])
print(vector_column)

[2 5 6]
[[1]
 [6]
 [3]]


#### Discussion
Numpy's main data structure is the multidimensional array

#### See Also
* Vectors, Math is Fun (https://www.mathsisfun.com/algebra/vectors.html)
* Euclidian vector, Wikipedia (https://en.wikipedia.org/wiki/Euclidean_vector)

### 1.2 Creating a Matrix

#### Problem
You need to create a matrix.

#### Solution
Use Numpy to create a two-dimensional array:

#### Discussion
To create a matrix we can use a NumPy two-dimensional array. In our solution, the matrix contains three rows and two columns (a column of 1s and a column of 2s)

NumPy actually has a dedicated matrix data structure:

In [ ]:
# load library
import numpy as np

# create a matrix
matrix=np.array([[1, 2, 3],[1, 3, 4],[1, 4, 5]])
print(matrix)

[[1 2 3]
 [1 3 4]
 [1 4 5]]


However the matrix data structure is not recommended for two reasons. First, arrays are the de facto standard data structure of NumPy. Second the vast majority of NumPy operations return arrays, not matrix objects.

#### See Also
* Matrix, Wikipedia (https://en.wikipedia.org/wiki/Matrix_(mathematics)
* Matrix, Wolfram MathWorld (http://mathworld.wolfram.com/Matrix.html)

### 1.3 Creating a Sparse Matrix
#### Problem
Given data with very few nonzero values, you want to efficiently represent it.

#### Solution
Create a sparse matrix:

In [ ]:
# load libraries
import numpy as np
from scipy import sparse

# create a matrix
matrix = np.array([[0, 4],
                  [0, 1],
                  [3, 0]])

# create compressed sparse row (CSR) matrix
matrix_sparse = sparse.csr_matrix(matrix)
print(matrix)
print(matrix_sparse)

[[0 4]
 [0 1]
 [3 0]]
  (0, 1)	4
  (1, 1)	1
  (2, 0)	3


#### Discussion
A frequent situation in machine learning is having a huge amount of data; however most of the elements in the data are zeros. For example, imagine a matrix where the columns are every movie on Netflix, the rows are every Netflix user, and the values are how many times a user has watched that particular movie. This matrix would have tens of thousands of columns and millions of rows! However, since most users do not watch most movies, the vast majority of elements would be zero.

Sparse matricies only store nonzero elements and assume all other values will be zero, leading to significant computational savings. In our solution, we created a Numpy array with two nonzero values, then converted it into a sparse matrix. If we view the sparse matrix we can see that only the nonzero values are stored:

In [ ]:
# view sparse matrix
print(matrix_sparse)


  (1, 1)	1
  (2, 0)	3


There are a number of types of sparse matrices. However, in compressed sparse row (CSR) matrices, (1, 1) and (2, 0) represent the (zero-indexed) indices of the non-zero values 1 and 3, respectively. For example, the element 1 is in the second row and second column. We can see the advantage of sparse matrices if we create a much larger matrix with many more zero elements and then compare this larger matrix with our original sparse matrix:

In [ ]:
# create larger matrix
x = np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                         [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
                         [3, 0, 0, 0, 0, 0, 0, 0, 0, 0]])


# create compressed sparse row (CSR) matrix
y = sparse.csr_matrix(x)

# view original sparse matrix
print(y)

  (1, 1)	1
  (2, 0)	3


In [ ]:
# view larger sparse matrix


As we can see, despite the fact that we added many more zero elements in the larger matrix, its sparse representation is exactly the same as our original sparse matrix. That is, the addition of zero elements did not change the size of the sparse matrix.

As mentioned, there are many different types of sparse matrices, such as compressed sparse column, list of lists, and dictionary of keys. While an explanation of the different types and their implications is outside the scope, it is worth noting that while there is no “best” sparse matrix type, there are meaningful differences between them and we should be conscious about why we are choosing one type over another.

#### See Also
* Sparse matrices, SciPy documentation (https://docs.scipy.org/doc/scipy/reference/sparse.html)
* 101 Ways to Store a Sparse Matrix (https://medium.com/@jmaxg3/101-ways-to-store-a-sparse-matrix-c7f2bf15a229)

### 1.4 Selected Elements
#### Problem
You need to select one or more elements in a vector or matrix.

#### Solution
NumPy's arrays make that easy

In [ ]:
# load library
import numpy as np

# create row vector
vector = np.array([1, 2, 3, 4, 5, 6])

# create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# select the third element of vector
vector[2:6]

array([3, 4, 5, 6])

In [ ]:
# select second row, second column
matrix[1,1]

5

#### Discussion
Like most things in Python, NumPy arrays are zero-indexed, meaning that the index of the first element is 0, not 1. With that caveat, NumPy offers a wide variety of methods for selecting (i.e., indexing and slicing) elements or groups of elements in arrays:

In [ ]:
# Select all elements of a vector
vector[:]

array([1, 2, 3, 4, 5, 6])

In [ ]:
# select everything up to and including the third element
vector[:2]

array([1, 2])

In [ ]:
# select the last element
vector[-5]

2

In [ ]:
# select the first two rows and all columns of a matrix
matrix[:2, :]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# select all rows and the second column
matrix[:,1:2]

array([[2],
       [5],
       [8]])

### 1.5 Describing a Matrix
#### Problem
You want to describe the shape, size, and dimensions of the matrix

#### Solution
Use shape, size, and ndim:

In [ ]:
# load library
import numpy as np

# create matrix
ix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

# view number of rows and columns
matrix.shape

(3, 4)

In [ ]:
# view number of elements (rows * columns)
ix.size

12

In [ ]:
# view number of dimensions
ix.ndim

2

#### Discussion
This might seem basic (and it is); however, time and again it will be valuable to check the shape and size of an array both for further calculations and simply as a gut check after some operation

### 1.6 Applying Operations to Elements
#### Problem
You want to apply some function to multiple elements in an array.

#### Solutions
Use NumPy's vectorize:

In [ ]:
# load library
import numpy as np

# create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# create function that adds 1000 to something
add_1000 = lambda i: i + 1000

# create vectorized function
vectorized_add_1000 = np.vectorize(add_1000)

# apply function to all elementsin matrix
vectorized_add_1000(matrix)

array([[1001, 1002, 1003],
       [1004, 1005, 1006],
       [1007, 1008, 1009]])

In [ ]:
# another way to define a function
def add_1000(i):
   i=i+1000
   return i


#### Discusion
A lambda function is a small anonymous function. A lambda function can take any number of arguments, but can only have one expression.
NumPy’s vectorize class converts a function into a function that can apply to all elements in an array or slice of an array. It’s worth noting that vectorize is essentially a for loop over the elements and does not increase performance. Furthermore, NumPy arrays allow us to perform operations between arrays even if their dimensions are not the same (a process called broadcasting). For example, we can create a much simpler version of our solution using broadcasting:

In [ ]:
# add 1000 to all elements
matrix + 1000

array([[1001, 1002, 1003],
       [1004, 1005, 1006],
       [1007, 1008, 1009]])

### Finding Maximum and Minimum Values
#### Problem
You need to find the maximum or minimum value in an array.

#### Solution
Use NumPy's max and min:

In [ ]:
# load library
import numpy as np

# create matrix
matrix = np.array([[1, 200, 3],
                   [4, 5, 6],
                   [7, 20, 9]])

# rreturn maximum element
np.max(matrix)

200

In [ ]:
# return minimum element
np.min(matrix)


1

#### Discussion
Often we want to know the maximum and minimum value in an array or subset of an array. This can be accomplished with the max and min methods. Using the axis parameter we can also apply the operation along a certain axis:

In [ ]:
# find maximum element in each column
np.max(matrix, axis=0)

array([7, 8, 9])

In [ ]:
# find maximum element in each row
np.max(matrix, axis=1)

array([3, 6, 9])

# Unsolved Tutorial sheet
### 1.8 Calculating the Average, Variance, and Standard Deviation

#### Problem
You want to calculate some descriptive statistics about an array.

#### Solution
Use NumPy's mean, var, and std:

In [ ]:
# load library
import numpy as np

# create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# return mean
np.mean(matrix)


5.0

In [ ]:
# return variance
np.var(matrix)


6.666666666666667

In [ ]:
# return standard deviation
np.std(matrix)


2.581988897471611

#### Discussion
Just like with max and min, we can easily get descriptive statistics about the whole matrix or do calculations alon a single axis:

In [ ]:
# find the mean value in each column
np.mean(matrix, axis=0)


array([4., 5., 6.])

### 1.9 Reshaping Arrays
#### Problem
You want to change the shape (number of rows and columns) of an array without changing the element values.

#### Solution
Use NumPy's reshape:

In [ ]:
# load library
import numpy as np

# create 4x3 matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9],
                   [10, 11, 12]])

# reshape matrix into 2x6 matrix
new_matrix = matrix.reshape(2,6)
print(new_matrix)


[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


#### Discussion
reshape allows us to restructure an array so that we maintain the same data but it is organized as a different number of rows and columns. The only requirement is that the shape of the original and new matrix contain the same number of elements (i.e., the same size). We can see the size of a matrix using size:

In [ ]:
matrix.size

12

One useful argument in reshape is -1, which effectively means “as many as needed,” so reshape(-1, 1) means one row and as many columns as needed:

In [ ]:
matrix.reshape(1, -1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

Finally, if we provide one integer, reshape will return a 1D array of that length:

In [ ]:
matrix.reshape(12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

### 2.0 Introduction to Linear Algebra
#### Problem
You want to calculate eigenvalues and eigenvectors of a given matrix.

#### Solution
Use NumPy's eig from linear algebra

In [ ]:
from numpy import linalg
A= np.array([[5, 3], [-6, -4]])
A

array([[ 5,  3],
       [-6, -4]])

In [ ]:
#Write command to find and print eigenvalues and eigenvectors of mtarix A
w, v = np.linalg.eig(A)

print(w)
print(v)

[ 2. -1.]
[[ 0.70710678 -0.4472136 ]
 [-0.70710678  0.89442719]]


#### Problem
You want to find inverse of a given matrix.

#### Solution
Use NumPy's inv from linear algebra

In [ ]:
#Write command to find and print inverse of mtarix A
print(np.linalg.inv(A))

[[ 2.   1.5]
 [-3.  -2.5]]


For more on Linear Algebra functions from numpy
https://numpy.org/doc/stable/reference/routines.linalg.html

##**Post Lab Excercise**
### Prob 1 Write a program to check whether all elements in an array are non zero.

### Prob 2 Write a program to create a 2X2 matrix of ones and adding a border around it with zeros.

### Prob 3 Write a program to multiply a randomly generated 4X3 size matrix to randomly generated 3X5 size matrix.

### Prob 4 Write a program to solve the system of equations x0 + 2 * x1 = 1 and 3 * x0 + 5 * x1 = 2. [Hint: Use np.linalg.solve]

In [3]:
# 1st question
import numpy as NP

array1 = NP.array([2,4,6,8])
array2 = NP.array([1,3,5,0])

print(NP.all(array1))
print(NP.all(array2))


# 2nd question
import numpy as NP
x = NP.ones((2,2))
print("Original array:")
print(x)
print("0 on the border and 1 inside in the array")
x = NP.pad(x, pad_width=1, mode='constant', constant_values=0)
print(x)


# 3rd question
import numpy as NP
x = NP.random.random((4,3))
print("First matrix:")
print(x)
y = NP.random.random((3,5))
print("Second matrix:")
print(y)
z = NP.dot(x, y)
print("Dot product of two matrices:")
print(z)


# 4th question
a = NP.array([[1, 2], [3, 5]])
b = NP.array([1, 2])
x = NP.linalg.solve(a, b)
print(x)





True
False
Original array:
[[1. 1.]
 [1. 1.]]
0 on the border and 1 inside in the array
[[0. 0. 0. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 0. 0. 0.]]
First matrix:
[[0.93469243 0.80661688 0.72551724]
 [0.09656172 0.75951047 0.16825956]
 [0.12370298 0.75723373 0.59588974]
 [0.09923053 0.71013492 0.64790081]]
Second matrix:
[[0.48665838 0.89543769 0.95166135 0.73229211 0.90320051]
 [0.52082759 0.89038316 0.86435903 0.67730848 0.34493286]
 [0.92506739 0.83419007 0.72987094 0.73684701 0.60220174]]
Dot product of two matrices:
[[1.54613657 2.16037619 2.11625119 1.76539156 1.55935108]
 [0.59821802 0.9030808  0.87119156 0.70911583 0.45052092]
 [1.00582748 1.28208178 1.20716776 1.04254712 0.73176923]
 [1.01750114 1.26161936 1.18112937 1.03104992 0.72474093]]
[-1.  1.]
